name: Build and Run

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get repo name
      id: repo-name
      run: echo "::set-output name=value::$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')"

    - name: Configure
      run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Run
      run: ./build/${{ steps.repo-name.outputs.value }}
